services:
  api:
    build: .docker/api
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ~/.composer:/home/composer/
    environment:
      - XDEBUG_CONFIG
      - DB_ADAPTER
      - DP_DRIVER
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
  postgres:
    env_file:
      - .env
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data