name: api
on: pull_request

jobs:
  api:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0' , '8.1']

    name: php${{ matrix.php-versions }}

    steps:
      - name: Checkout app
        uses: actions/checkout@master

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Set up dependencies
        run: composer install

      - name: Run behat
        env:
          BEHAT_ROOT_DIR: public
        run: vendor/bin/behat features/zap.feature:3