name: PHPUnit
on: pull_request

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']
        coverage: ['xdebug']
        xdebug_mode: ['coverage']
        server-versions: ['master']
    name: php${{ matrix.php-versions }}

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432/tcp
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: zapimoveis
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: ${{ matrix.coverage }}
          extensions: pdo_pgsql

      - name: Install dependencies
        run: composer i

      - name: Run phpunit
        env:
          XDEBUG_MODE: ${{ matrix.xdebug_mode }}
          DB_ADAPTER: pgsql
          DB_DRIVER: pdo_pgsql
          DB_HOST: 127.0.0.1
          DB_NAME: zapimoveis
          DB_USER: root
          DB_PASSWORD: rootpassword
          DB_PORT: 5432
        run: |
          vendor/bin/phinx migrate
          vendor/bin/phpunit --testsuite unit

      - name: Upload coverage results to Coveralls
        if: matrix.xdebug_mode == 'coverage'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php-versions }}
        run: |
          composer global require php-coveralls/php-coveralls --no-progress --no-interaction
          php-coveralls --coverage_clover=storage/logs/clover.xml --json_path=storage/logs/coveralls-upload.json -vvv

  finish-coverage:
    needs: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Let Coveralls know that all tests have finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true